version: "3.9"

services:
  traefik:
    image: traefik:v3.1
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - TZ=${TZ}
    networks:
      - conexao-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/traefik.yml:ro
      - ./traefik/dynamic:/dynamic:ro
      - ./letsencrypt:/letsencrypt
      - ./secrets:/secrets:ro
    labels:
      - traefik.enable=true
      # Dashboard seguro
      - traefik.http.routers.dashboard.rule=Host(`${TRAEFIK_HOST}`)
      - traefik.http.routers.dashboard.entrypoints=websecure
      - traefik.http.routers.dashboard.tls.certresolver=letsencrypt
      - traefik.http.routers.dashboard.service=api@internal
      - traefik.http.middlewares.dashboard-auth.basicauth.usersfile=/secrets/traefik-basicauth
      - traefik.http.routers.dashboard.middlewares=dashboard-auth,security-headers@file

networks:
  conexao-network:
    external: true
